# EXCEL로 만든 인공신경망을 pytorch의 Tensor 클래스을 이용하여 만들기

In [1]:
import torch

필요한 함수의 정의하기

In [2]:
def ReLU_func(outputs):
    final_outputs = torch.maximum(torch.tensor(0),outputs)
    return final_outputs

def softmax(outputs):
    exp_outputs = torch.exp(outputs)
    softmax = exp_outputs / torch.sum(exp_outputs, dim=1, keepdims=True)
    return softmax

def cross_entropy(outputs, labels):
    m = outputs.shape[0]
    p = softmax(outputs)
    labels = torch.argmax(labels, dim=1)
    loss = -torch.log(p[range(m),labels])
    return loss

Weigh 값 설정하기

In [3]:
w_ih = torch.Tensor([[1, -2, 3], [-2, 5, 3]])
w_ho = torch.Tensor([[3, -2, 4], [-1, 2, 3], [2, -2, -4]])

Batch가 3인 Input 값과 Labels값의 입력하기

In [4]:
input = torch.Tensor([[2,-4], [0,3], [-6,2]])
labels = torch.Tensor([[1,0,0], [0,1,0], [0,0,1]])

L1의 활성화 함수 전의 값 구하기

In [5]:
L1 = input.matmul(w_ih)
print(L1)

tensor([[ 10., -24.,  -6.],
        [ -6.,  15.,   9.],
        [-10.,  22., -12.]])


ReLU의 적용하기

In [6]:
L1 = ReLU_func(L1)
print(L1)

tensor([[10.,  0.,  0.],
        [ 0., 15.,  9.],
        [ 0., 22.,  0.]])


Output 구하기

In [7]:
outputs = L1.matmul(w_ho)
print(outputs)

tensor([[ 30., -20.,  40.],
        [  3.,  12.,   9.],
        [-22.,  44.,  66.]])


Softmax의 적용

In [8]:
so = softmax(torch.Tensor(outputs))
print(so)

tensor([[4.5398e-05, 8.7561e-27, 9.9995e-01],
        [1.1754e-04, 9.5246e-01, 4.7420e-02],
        [6.0546e-39, 2.7895e-10, 1.0000e+00]])


sample별로 loss 구하기

In [9]:
loss = cross_entropy(outputs, labels)
print(loss)

tensor([10.0000,  0.0487, -0.0000])


최종 loss 구하기

In [10]:
loss = torch.sum(loss) / 3
print(loss)

tensor(3.3496)


# EXCEL과 같은 답이 나오는가?
## 아니면 이유가 무엇인가?
답변 하시오

다른 답이 나옴.  
이유:같은 입력을 하더라도 Excel과 PyTorch는 데이터 처리 방식, 연산 방법, 데이터 유형 등에서 차이가 있으므로 결과가 다를 수 있다.
1. Excel은 수식 계산을 사용하여 결과를 생성하고 실제로 텐서 연산을 수행하지는 않는다. 따라서 일부 수학적 계산에서 오차가 발생할 수 있다.

2. Excel은 대규모 데이터 집합을 다루기에는 적합하지 않다. 메모리 제한이 있기 때문에 대용량 데이터 처리에 어려움이 있기 때문이다. 반면, PyTorch는 GPU를 사용하여 연산을 수행하기 때문에 빠르게 대규모 데이터 처리가 가능하다.

3. Excel과 PyTorch는 데이터 유형과 저장 방식이 다르다. Excel은 일반적으로 텍스트 데이터를 처리하며, PyTorch는 다차원 배열로 처리합니다. 이러한 차이로 인해 데이터 변환이 필요할 수 있으며, 이는 결과에도 영향을 미칠 수 있다.

4. Excel은 일반적으로 데이터를 행렬 형태로 처리합니다. PyTorch는 텐서를 사용하여 다차원 배열을 처리한다. 이러한 차이로 인해 데이터의 차원이나 형태가 다를 수 있으며, 이는 결과의 차이를 일으킬 수 있다.

In [11]:
print("2019125022 류재혁")

2019125022 류재혁
